name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout=3m

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Prettier
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: "--check **/*.{md,yml}"
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v7.2.0
        with:
          # Uncomment below to run on all files irrespective of change status.
          # incremental_files_only: false
          verbose: true
